spawnPos = "TrafficLane.112";
goal = "TrafficLane.111" at 220;
ve = 5.556;

route1 = [
    "TrafficLane.112" max-velocity(ve),
    cut-out(90, ve, 1.4, 6),
    "TrafficLane.111" max-velocity(ve)
];

npc1 = NPC("hatchback", spawnPos forward 20, goal, route1, [acceleration(1), delay-move-until-ego-engaged(1)]);
npc2 = NPC("hatchback", _, [delay-spawn(_)]);

ego = Ego(spawnPos, "TrafficLane.112" at 190, [max-velocity(ve)]);

run(ego, [npc1,npc2], [saving-timeout(50)]);
