spawnPos = "TrafficLane.111" at 2;
goal = "TrafficLane.111" at 90;
ve = 5.556;

route1 = [
    "TrafficLane.111" max-velocity(ve)
];

npc1 = NPC("smallcar", spawnPos forward 15, goal, route1, 
    [acceleration(1), 
     deceleration(9.81), 
     aggressive-driving,
     delay-move-until-ego-engaged(1)]);

npc2 = NPC("smallcar", _, [delay-spawn(_)]);

ego = Ego(spawnPos, "TrafficLane.111" at 130, [max-velocity(ve)]);

run(ego, [npc1,npc2], [saving-timeout(50)]);